site_name: 科幻-脑洞-神话

copyright: Copyright © 晓忢

nav:
  - 主页: index.md
  - 世界神话故事关联: 世界神话故事关联.md
  - 你以为的-事实上的: 你以为的-事实上的.md
  - 地球编年史结论: 地球编年史结论.md
  - 生命3.0-AI人工智能: 生命3.0-AI人工智能.md
  - 未来科技: 未来科技.md
  - 记忆-意识-灵魂-量子-机器人-永生-修仙: 记忆-意识-灵魂-量子-机器人-永生-修仙.md
theme:
  name: material
  language: 'zh'  #配置语言
  palette:  # 颜色
    primary: 'cyan'
    accent: 'neon'
plugins:
  - search
markdown_extentions:
  - admonition #提示块